= Problem Set 6: Sentimental

**Due: Friday, November 25, at 23:59.**

== Objectives

* Port some programs from C to Python.
* Analyze some sentiments.

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problems is not permitted (unless explicitly stated otherwise) except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code or writing to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on quizzes and tests is not permitted at all. Collaboration on the final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your instructor. If a violation of this policy is suspected and confirmed, your instructor reserves the right to impose local sanctions on top of any disciplinary outcome that may include an unsatisfactory or failing grade for work submitted or for the course itself.

=== Reasonable

* Communicating with classmates about problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code, such as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past years' quizzes, tests, and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own solutions to problems online so that others might help you identify and fix a bug or other issue.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problems or your own final project.
* Whiteboarding solutions to problems with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problems.
* Failing to cite (as with comments) the origins of code, writing, or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz or test.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problems to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problems online or elsewhere.
* Splitting a problem's workload with another individual and combining your work (unless explicitly authorized by the problem itself).
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem and basing your own solution on it.

== Getting Ready

[source,bash]
----
update50
mkdir ~/workspace/pset6/
cd ~/workspace/pset6/
----

== Problems

All code that you write should be consistent with https://www.python.org/dev/peps/pep-0008/[Style Guide for Python Code], otherwise known as PEP 8.

. Implement either of the below exactly as specified but in Python:

** http://docs.cs50.net/problems/mario/less/mario.html[Mario], less comfortable, in a file called `mario.py` in `pset6/`.

** http://docs.cs50.net/problems/mario/more/mario.html[Mario], more comfortable, in a file called `mario.py` in `pset6/`.

. Implement either of the below exactly as specified but in Python:

** http://docs.cs50.net/problems/greedy/greedy.html[Greedy], less comfortable, in a file called `greedy.py` in `pset6/`.

** http://docs.cs50.net/problems/credit/credit.html[Credit], more comfortable, in a file called `credit.py` in `pset6/`.

. Implement any (one) of the below exactly as specified but in Python:

** http://docs.cs50.net/problems/caesar/caesar.html[Caesar], less comfortable, in a file called `caesar.py` in `pset6/`.

** http://docs.cs50.net/problems/vigenere/vigenere.html[Vigenère], less comfortable, in a file called `vigenere.py` in `pset6/`.

** http://docs.cs50.net/problems/crack/crack.html[Crack], more comfortable, in a file called `crack.py` in `pset6/`.

. Implement http://docs.cs50.net/problems/sentiments/sentiments.html[Sentiments] in `pset6/sentiments/`.

No `check50` for these!

== Hints

* Be sure to use Python 3, not Python 2.

* If a program is in a file called, say, `foo.py`, you can run that program with `python foo.py`.

* For Mario, Greedy, Credit, Caesar, Vigenère, and Crack, it is *reasonable* to look at your own implementations thereof in C and others' implementations thereof in C, including the staff’s implementations thereof (and postmortems) in C. It is *not reasonable* to look at others' implementations of the same in Python. It is *not reasonable* to look at others' implementations of Sentiments.

* Consider this problem set an opportunity not only to port your own prior work from C to Python but to improve upon your earlier designs using lessons learned since!

* When porting code from C to Python in CS50 IDE, you might want to select *View > Layout > Horizontal Split* so that you can see both side by side.

* Insofar as a goal of this problem set is to teach you how to teach yourself a new language, keep in mind that these acts are not only *reasonable*, per the syllabus, but encouraged toward that end:

** Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.

** Turning to the web or elsewhere for instruction beyond the course’s own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set’s problems or your own final project.

* You’re welcome to use the CS50 Library for Python, which includes `get_float`, `get_int`, and `get_string`. Just remember to include

[source,bash]
import cs50

atop your code. Or you can use https://docs.python.org/3/library/functions.html#input[`input`] and validate users' input yourself.

* You might find https://docs.python.org/3/library/functions.html#chr[`chr`] and/or https://docs.python.org/3/library/functions.html#ord[`ord`] of help.

* You might find these references of interest:

** https://docs.python.org/3/reference/index.html[The Python Language Reference]

** https://docs.python.org/3/library/[The Python Standard Library]

** https://docs.python.org/3/tutorial/index.html[The Python Tutorial]

== Walkthrough

=== Problems 1 - 3

video::_qm372js7YI[youtube,height=540,width=960]

=== Problem 4

See http://docs.cs50.net/problems/sentiments/sentiments.html#walkthrough[Sentiments]

== FAQs

=== AttributeError: 'module' object has no attribute `get_`

If seeing this error (for `cs50.get_char`, `cs50.get_float`, `cs50.get_int`, or `cs50.get_string`), try executing the below (which fixes a bug in an earlier version of the CS50 Library for Python):

[source,bash]
----
sudo chmod -R a+rX /usr/lib/python2.7/dist-packages/cs50
sudo chmod -R a+rX /usr/lib/python3/dist-packages/cs50
----

=== ImportError: No module named 'sqlalchemy'

If seeing this error, execute

[source,bash]
pip install --user sqlalchemy

to resolve!

== How to Submit

Toward CS50 IDE's top-left corner, within its "file browser" (not within a terminal window), control-click or right-click your `pset6` folder and then select *Download*. You should find that your browser has downloaded `pset6.zip`.

This was Problem Set 6.
